# Generated by Django 3.2.9 on 2021-11-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название типа вторичной миссии')),
            ],
            options={
                'verbose_name': 'Тип вторичной миссии',
                'verbose_name_plural': 'Типы вторичной миссии',
            },
        ),
        migrations.CreateModel(
            name='RulesVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название пака правил')),
                ('actual_version', models.BooleanField(default=True, verbose_name='Актуальная ли это версия')),
                ('short_name', models.CharField(max_length=5, verbose_name='Короткое название')),
            ],
            options={
                'verbose_name': 'Набор правил',
                'verbose_name_plural': 'Наборы правил',
            },
        ),
        migrations.CreateModel(
            name='SecondaryObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название миссии')),
                ('objective_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectives.objectivetype', verbose_name='Тип миссии')),
                ('rule_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectives.rulesversion', verbose_name='Откуда правила')),
            ],
        ),
        migrations.AddField(
            model_name='objectivetype',
            name='rule_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objectives.rulesversion', verbose_name='Откуда правила'),
        ),
    ]
